Repo cleanup
XENONnT/strax_auxiliary_files pull request #9
Opened 2020-12-03 17:21 UTC by jorana

2020-12-07 16:27 UTC, ramirezdiego approved these changes

2020-12-07 17:32 UTC, zhut19 approved these changes

2020-12-10 09:51 UTC, jorana commented
@l-althueser @petergaemers please approve. I'm merging today!

2020-12-10 10:00 UTC, l-althueser requested changes
@petergaemers the file `Xenon1T_WholeLXe_Pb21....root` can be deleted?

2020-12-10 10:16 UTC, petergaemers commented
Yes that can be deleted

2020-12-10 10:17 UTC, petergaemers approved these changes

2020-12-10 12:14 UTC, merged